import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Button, Center } from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useState } from "react";
import { Contract, providers, utils } from "ethers";
import { useProvider, useSigner, useContract } from "wagmi";
import { ABI, contractAddress } from "@/constants/constants";
export default function Home() {
  const { data: signer, isError, isLoading } = useSigner();
  console.log(signer);
  const mintNft = async () => {
    const nftContract = new Contract(contractAddress, ABI, signer);
    const tx = await nftContract.mint(1);
    await tx.wait();
  };

  const [balance, setBalance] = useState();

  const showBalance = async () => {
    const nftContract = new Contract(contractAddress, ABI, signer);
    const tx = await nftContract.balanceOf(signer._address);
    const abx = BigInt(tx._hex).toString();
    setBalance(abx);
    console.log(abx);
  };
  return (
    <>
      <Head>
        <title>Mint NFT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        bgGradient={
          "linear-gradient( 113deg,  rgba(251,250,205,1) 24.4%, rgba(247,163,205,1) 53.7%, rgba(141,66,243,1) 99.2% );"
        }
        height={"100vh"}
        fontFamily="Courier New, Courier, monospace"
      >
        {/* navigation */}
        <Box
          padding={"25px 20px"}
          display={"flex"}
          justifyContent={"right"}
          alignItems={"center"}
        >
          <Box
            display={"flex"}
            justifyContent={"space-evenly"}
            alignItems={"center"}
            width={"50%"}
          >
            <Box display={"flex"} fontWeight={"bold"}>
              About
            </Box>
            <ConnectButton />
          </Box>
        </Box>
        {/* main content */}
        <Box h={"60vh"} display={"flex"} flexDir={"column"}>
          <Box marginBottom={8} fontWeight={"bold"}>
            Mint your BAYC NFT now. You can have at max 5 NFTs.
          </Box>
          <Box width={"50%"}>
            <Button width={"18%"} onClick={mintNft} marginRight={8}>
              Mint NFT
            </Button>
            <Button width={"18%"} onClick={showBalance}>
              Show Balance
            </Button>
          </Box>
          <Box fontWeight={"bold"}>
            {balance ? `You have ${balance} BAYC NFTs` : ""}
          </Box>
        </Box>
      </Box>
    </>
  );
}
